version: '3.4'

services:
  nodemelichallenge:
    image: nodemelichallenge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 4444
    ports:
      - 4444:4444
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
