version: '3.4'

services:
  nodemelichallenge:
    image: nodemelichallenge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4444:4444
